version: '3.8'

services:
  # Backend only for development (frontend runs via npm start)
  backend-dev:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: murdermystery-backend-dev
    ports:
      - "8080:8080"
    env_file:
      - .env.development
    environment:
      - NODE_ENV=development
    volumes:
      # Mount source code for hot reload
      - ./server:/app
      - /app/node_modules
      # Persistent storage for data files
      - ./server/data:/app/data
    restart: unless-stopped
    command: npm run dev

networks:
  default:
    name: murdermystery-network-dev